GLOB sdist-make: /home/holmanb/cloud-init-impish/setup.py
integration-tests inst-nodeps: /home/holmanb/cloud-init-impish/.tox/.tmp/package/1/cloud-init-22.1.zip
integration-tests installed: adal==1.2.7,appdirs==1.4.4,applicationinsights==0.11.10,argcomplete==1.12.3,attrs==21.4.0,autopage==0.5.0,azure-cli-core==2.20.0,azure-cli-telemetry==1.0.6,azure-common==1.1.28,azure-core==1.23.0,azure-mgmt-compute==14.0.0,azure-mgmt-core==1.3.0,azure-mgmt-network==13.0.0,azure-mgmt-resource==13.0.0,bcrypt==3.2.0,boto3==1.21.20,botocore==1.24.20,cachetools==5.0.0,certifi==2021.10.8,cffi==1.15.0,charset-normalizer==2.0.12,circuitbreaker==1.3.2,cliff==3.10.1,cloud-init @ file:///home/holmanb/cloud-init-impish/.tox/.tmp/package/1/cloud-init-22.1.zip,cmd2==2.4.0,colorama==0.4.4,configobj==5.0.6,cryptography==3.3.2,debtcollector==2.5.0,decorator==5.1.1,dogpile.cache==1.1.5,google-api-core==2.7.1,google-api-python-client==2.41.0,google-auth==2.6.0,google-auth-httplib2==0.1.0,googleapis-common-protos==1.55.0,httplib2==0.20.4,humanfriendly==9.2,idna==3.3,iniconfig==1.1.1,iso8601==1.0.2,isodate==0.6.1,Jinja2==3.0.3,jmespath==0.10.0,jsonpatch==1.32,jsonpointer==2.2,jsonschema==4.4.0,keystoneauth1==4.5.0,knack==0.8.0rc2,MarkupSafe==2.1.1,msal==1.17.0,msgpack==1.0.3,msrest==0.6.21,msrestazure==0.6.4,munch==2.5.0,netaddr==0.8.0,netifaces==0.11.0,oauthlib==3.2.0,oci==2.60.1,openstacksdk==0.61.0,os-service-types==1.7.0,osc-lib==2.5.0,oslo.config==8.8.0,oslo.i18n==5.1.0,oslo.serialization==4.3.0,oslo.utils==4.12.2,packaging==21.3,paramiko==2.10.2,pbr==5.8.1,pkginfo==1.8.2,pluggy==1.0.0,portalocker==1.7.1,prettytable==3.2.0,protobuf==3.19.4,psutil==5.9.0,py==1.11.0,pyasn1==0.4.8,pyasn1-modules==0.2.8,pycloudlib @ git+https://github.com/canonical/pycloudlib.git@44206bb95c49901d994c9eb772eba07f2a1b6661,pycparser==2.21,Pygments==2.11.2,PyJWT==1.7.1,PyNaCl==1.5.0,pyOpenSSL==19.1.0,pyparsing==2.4.7,pyperclip==1.8.2,pyrsistent==0.18.1,pytest==7.1.0,python-cinderclient==8.3.0,python-dateutil==2.8.2,python-keystoneclient==4.4.0,python-novaclient==17.7.0,python-openstackclient==5.8.0,python-simplestreams @ git+https://git.launchpad.net/simplestreams@21c5bba2a5413c51e6b9131fc450e96f6b46090d,pytz==2021.3,PyYAML==6.0,requests==2.27.1,requests-oauthlib==1.3.1,requestsexceptions==1.4.0,rfc3986==2.0.0,rsa==4.8,s3transfer==0.5.2,simplejson==3.17.6,six==1.16.0,stevedore==3.5.0,tabulate==0.8.9,toml==0.10.0,tomli==2.0.1,typing_extensions==4.1.1,uritemplate==4.1.1,urllib3==1.26.9,wcwidth==0.2.5,wrapt==1.14.0
integration-tests run-test-pre: PYTHONHASHSEED='1634389023'
integration-tests run-test: commands[0] | /home/holmanb/cloud-init-impish/.tox/integration-tests/bin/python -m pytest --log-cli-level=INFO tests/integration_tests/modules/test_command_output.py::test_runcmd
============================= test session starts ==============================
platform linux -- Python 3.10.2+, pytest-7.1.0, pluggy-1.0.0
cachedir: .tox/integration-tests/.pytest_cache
rootdir: /home/holmanb/cloud-init-impish, configfile: tox.ini
collected 1 item

tests/integration_tests/modules/test_command_output.py::test_runcmd 
-------------------------------- live log setup --------------------------------
2022-03-16 21:54:44 INFO      integration_testing:clouds.py:78 Detected image: image_id=impish os=ubuntu release=impish
2022-03-16 21:54:44 INFO      integration_testing:clouds.py:78 Detected image: image_id=impish os=ubuntu release=impish
2022-03-16 21:54:51 INFO      integration_testing:clouds.py:107 Settings:
CLOUD_INIT_SOURCE=PROPOSED
COLLECT_LOGS=ON_ERROR
EXISTING_INSTANCE_ID=None
INSTANCE_TYPE=None
KEEP_IMAGE=False
KEEP_INSTANCE=False
LOCAL_LOG_PATH=/tmp/cloud_init_test_logs
OS_IMAGE=impish
PLATFORM=gce
RUN_UNSTABLE=False
2022-03-16 21:54:51 INFO      integration_testing:conftest.py:148 Setting up environment for gce
2022-03-16 21:54:51 INFO      integration_testing:clouds.py:156 Launching instance with launch_kwargs:
image_id=projects/ubuntu-os-cloud-devel/global/images/daily-ubuntu-2110-impish-v20220316
user_data=None
2022-03-16 21:55:03 INFO      pycloudlib.instance:instance.py:183 executing: sh -c whoami
2022-03-16 21:55:03 WARNING   pycloudlib.instance:instance.py:344 The specified key (/home/holmanb/.ssh/id_rsa) requires a passphrase. If you have not added this key to a running SSH agent, you will see failures to connect after a long timeout.
2022-03-16 21:55:19 INFO      pycloudlib.instance:instance.py:183 executing: sh -c whoami
2022-03-16 21:55:19 WARNING   pycloudlib.instance:instance.py:344 The specified key (/home/holmanb/.ssh/id_rsa) requires a passphrase. If you have not added this key to a running SSH agent, you will see failures to connect after a long timeout.
2022-03-16 21:55:20 INFO      pycloudlib.instance:instance.py:183 executing: sh -c whoami
2022-03-16 21:55:20 WARNING   pycloudlib.instance:instance.py:344 The specified key (/home/holmanb/.ssh/id_rsa) requires a passphrase. If you have not added this key to a running SSH agent, you will see failures to connect after a long timeout.
2022-03-16 21:55:22 INFO      pycloudlib.instance:instance.py:183 executing: sh -c whoami
2022-03-16 21:55:22 WARNING   pycloudlib.instance:instance.py:344 The specified key (/home/holmanb/.ssh/id_rsa) requires a passphrase. If you have not added this key to a running SSH agent, you will see failures to connect after a long timeout.
2022-03-16 21:55:23 INFO      pycloudlib.instance:instance.py:183 executing: sh -c whoami
2022-03-16 21:55:23 WARNING   pycloudlib.instance:instance.py:344 The specified key (/home/holmanb/.ssh/id_rsa) requires a passphrase. If you have not added this key to a running SSH agent, you will see failures to connect after a long timeout.
2022-03-16 21:55:24 INFO      pycloudlib.instance:instance.py:183 executing: sh -c whoami
2022-03-16 21:55:24 WARNING   pycloudlib.instance:instance.py:344 The specified key (/home/holmanb/.ssh/id_rsa) requires a passphrase. If you have not added this key to a running SSH agent, you will see failures to connect after a long timeout.
2022-03-16 21:55:24 INFO      paramiko.transport:transport.py:1873 Connected (version 2.0, client OpenSSH_8.4p1)
2022-03-16 21:55:24 INFO      paramiko.transport:transport.py:1873 Authentication (publickey) successful!
2022-03-16 21:55:27 INFO      pycloudlib.instance:instance.py:183 executing: which systemctl
2022-03-16 21:55:27 INFO      pycloudlib.instance:instance.py:183 executing: systemctl is-active cloud-init.target
2022-03-16 21:55:29 INFO      pycloudlib.instance:instance.py:183 executing: systemctl is-active cloud-init.target
2022-03-16 21:55:30 INFO      pycloudlib.instance:instance.py:183 executing: systemctl is-active cloud-init.target
2022-03-16 21:55:31 INFO      pycloudlib.instance:instance.py:183 executing: systemctl is-active cloud-init.target
2022-03-16 21:55:33 INFO      pycloudlib.instance:instance.py:183 executing: systemctl is-active cloud-init.target
2022-03-16 21:55:33 INFO      pycloudlib.instance:instance.py:183 executing: cloud-init status --wait --long
2022-03-16 21:55:33 INFO      integration_testing:clouds.py:163 Launched instance: GceInstance(instance_id=59218273507467843)
2022-03-16 21:55:33 INFO      pycloudlib.instance:instance.py:183 executing: sudo -- sh -c 'cloud-init --version'
2022-03-16 21:55:34 INFO      integration_testing:clouds.py:167 cloud-init version: /usr/bin/cloud-init 21.4-0ubuntu1~21.10.1
2022-03-16 21:55:34 INFO      pycloudlib.instance:instance.py:183 executing: sudo -- sh -c 'grep serial /etc/cloud/build.info'
2022-03-16 21:55:34 INFO      integration_testing:clouds.py:173 image serial: 20220316
2022-03-16 21:55:34 INFO      integration_testing:instances.py:160 Installing proposed image
2022-03-16 21:55:34 INFO      pycloudlib.instance:instance.py:183 executing: sudo -- sh -c 'echo deb "http://archive.ubuntu.com/ubuntu $(lsb_release -sc)-proposed main" >> /etc/apt/sources.list.d/proposed.list'
2022-03-16 21:55:34 INFO      pycloudlib.instance:instance.py:183 executing: sudo -- sh -c 'apt-get update -q'
2022-03-16 21:55:42 INFO      pycloudlib.instance:instance.py:183 executing: sudo -- sh -c 'apt-get install -qy cloud-init'
2022-03-16 21:55:48 INFO      pycloudlib.instance:instance.py:183 executing: sudo -- sh -c 'cloud-init -v'
2022-03-16 21:55:49 INFO      integration_testing:instances.py:147 Installed cloud-init version: 22.1-14-g2e17a0d6-0ubuntu1~21.10.2
2022-03-16 21:55:49 INFO      pycloudlib.instance:instance.py:183 executing: sh -c 'sudo cloud-init clean --logs'
2022-03-16 21:55:49 INFO      pycloudlib.instance:instance.py:183 executing: sh -c 'sudo rm -rf /var/log/syslog'
2022-03-16 21:56:44 INFO      integration_testing:instances.py:123 Created new image: projects/cloud-init-holmanb/global/images/i0-gce-integration-test-0316-155444-image
2022-03-16 21:56:45 INFO      integration_testing:conftest.py:154 Done with environment setup
2022-03-16 21:56:45 INFO      integration_testing:clouds.py:156 Launching instance with launch_kwargs:
image_id=projects/cloud-init-holmanb/global/images/i0-gce-integration-test-0316-155444-image
user_data=#cloud-config
output: { all: "| tee -a /var/log/cloud-init-test-output" }
final_message: "should be last line in cloud-init-test-output file"

2022-03-16 21:57:04 INFO      pycloudlib.instance:instance.py:183 executing: sh -c whoami
2022-03-16 21:57:04 WARNING   pycloudlib.instance:instance.py:344 The specified key (/home/holmanb/.ssh/id_rsa) requires a passphrase. If you have not added this key to a running SSH agent, you will see failures to connect after a long timeout.
2022-03-16 21:57:20 INFO      pycloudlib.instance:instance.py:183 executing: sh -c whoami
2022-03-16 21:57:21 WARNING   pycloudlib.instance:instance.py:344 The specified key (/home/holmanb/.ssh/id_rsa) requires a passphrase. If you have not added this key to a running SSH agent, you will see failures to connect after a long timeout.
2022-03-16 21:57:22 INFO      pycloudlib.instance:instance.py:183 executing: sh -c whoami
2022-03-16 21:57:22 WARNING   pycloudlib.instance:instance.py:344 The specified key (/home/holmanb/.ssh/id_rsa) requires a passphrase. If you have not added this key to a running SSH agent, you will see failures to connect after a long timeout.
2022-03-16 21:57:23 INFO      pycloudlib.instance:instance.py:183 executing: sh -c whoami
2022-03-16 21:57:23 WARNING   pycloudlib.instance:instance.py:344 The specified key (/home/holmanb/.ssh/id_rsa) requires a passphrase. If you have not added this key to a running SSH agent, you will see failures to connect after a long timeout.
2022-03-16 21:57:24 INFO      pycloudlib.instance:instance.py:183 executing: sh -c whoami
2022-03-16 21:57:24 WARNING   pycloudlib.instance:instance.py:344 The specified key (/home/holmanb/.ssh/id_rsa) requires a passphrase. If you have not added this key to a running SSH agent, you will see failures to connect after a long timeout.
2022-03-16 21:57:25 INFO      pycloudlib.instance:instance.py:183 executing: sh -c whoami
2022-03-16 21:57:25 WARNING   pycloudlib.instance:instance.py:344 The specified key (/home/holmanb/.ssh/id_rsa) requires a passphrase. If you have not added this key to a running SSH agent, you will see failures to connect after a long timeout.
2022-03-16 21:57:25 INFO      paramiko.transport:transport.py:1873 Connected (version 2.0, client OpenSSH_8.4p1)
2022-03-16 21:57:26 INFO      paramiko.transport:transport.py:1873 Authentication (publickey) successful!
2022-03-16 21:57:29 INFO      pycloudlib.instance:instance.py:183 executing: which systemctl
2022-03-16 21:57:30 INFO      pycloudlib.instance:instance.py:183 executing: systemctl is-active cloud-init.target
2022-03-16 21:57:31 INFO      pycloudlib.instance:instance.py:183 executing: systemctl is-active cloud-init.target
2022-03-16 21:57:32 INFO      pycloudlib.instance:instance.py:183 executing: systemctl is-active cloud-init.target
2022-03-16 21:57:33 INFO      pycloudlib.instance:instance.py:183 executing: systemctl is-active cloud-init.target
2022-03-16 21:57:33 INFO      pycloudlib.instance:instance.py:183 executing: cloud-init status --wait --long
2022-03-16 21:57:34 INFO      integration_testing:clouds.py:163 Launched instance: GceInstance(instance_id=4972322811845534706)
2022-03-16 21:57:34 INFO      pycloudlib.instance:instance.py:183 executing: sudo -- sh -c 'cloud-init --version'
2022-03-16 21:57:34 INFO      integration_testing:clouds.py:167 cloud-init version: /usr/bin/cloud-init 22.1-14-g2e17a0d6-0ubuntu1~21.10.2
2022-03-16 21:57:34 INFO      pycloudlib.instance:instance.py:183 executing: sudo -- sh -c 'grep serial /etc/cloud/build.info'
2022-03-16 21:57:34 INFO      integration_testing:clouds.py:173 image serial: 20220316
-------------------------------- live log call ---------------------------------
2022-03-16 21:57:34 INFO      pycloudlib.instance:instance.py:183 executing: sudo -- sh -c 'cat /var/log/cloud-init-test-output'
PASSED                                                                   [100%]
------------------------------ live log teardown -------------------------------
2022-03-16 21:58:26 INFO      integration_testing:clouds.py:194 Deleting snapshot image created for this testrun: projects/cloud-init-holmanb/global/images/i0-gce-integration-test-0316-155444-image


=============================== warnings summary ===============================
.tox/integration-tests/lib/python3.10/site-packages/_pytest/config/__init__.py:1202
  /home/holmanb/cloud-init-impish/.tox/integration-tests/lib/python3.10/site-packages/_pytest/config/__init__.py:1202: PytestRemovedIn8Warning: The --strict option is deprecated, use --strict-markers instead.
    self.issue_config_time_warning(

.tox/integration-tests/lib/python3.10/site-packages/simplestreams/contentsource.py:41
  /home/holmanb/cloud-init-impish/.tox/integration-tests/lib/python3.10/site-packages/simplestreams/contentsource.py:41: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
    from distutils.version import LooseVersion

tests/integration_tests/modules/test_command_output.py::test_runcmd
  /home/holmanb/cloud-init-impish/.tox/integration-tests/lib/python3.10/site-packages/simplestreams/mirrors/__init__.py:206: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
    LOG.warn("got ENOENT for (%s, %s), trying with trailing /",

tests/integration_tests/modules/test_command_output.py::test_runcmd
tests/integration_tests/modules/test_command_output.py::test_runcmd
tests/integration_tests/modules/test_command_output.py::test_runcmd
tests/integration_tests/modules/test_command_output.py::test_runcmd
tests/integration_tests/modules/test_command_output.py::test_runcmd
tests/integration_tests/modules/test_command_output.py::test_runcmd
  /home/holmanb/cloud-init-impish/.tox/integration-tests/lib/python3.10/site-packages/httplib2/__init__.py:147: DeprecationWarning: ssl.PROTOCOL_TLS is deprecated
    context = ssl.SSLContext(DEFAULT_TLS_VERSION)

tests/integration_tests/modules/test_command_output.py::test_runcmd
tests/integration_tests/modules/test_command_output.py::test_runcmd
  /home/holmanb/cloud-init-impish/.tox/integration-tests/lib/python3.10/site-packages/paramiko/transport.py:453: DeprecationWarning: setDaemon() is deprecated, set the daemon attribute instead
    self.setDaemon(True)

tests/integration_tests/modules/test_command_output.py::test_runcmd
tests/integration_tests/modules/test_command_output.py::test_runcmd
tests/integration_tests/modules/test_command_output.py::test_runcmd
tests/integration_tests/modules/test_command_output.py::test_runcmd
  /home/holmanb/cloud-init-impish/.tox/integration-tests/lib/python3.10/site-packages/paramiko/util.py:235: DeprecationWarning: currentThread() is deprecated, use current_thread() instead
    tid = id(threading.currentThread())

tests/integration_tests/modules/test_command_output.py: 26 warnings
  /home/holmanb/cloud-init-impish/.tox/integration-tests/lib/python3.10/site-packages/paramiko/channel.py:1069: DeprecationWarning: notifyAll() is deprecated, use notify_all() instead
    self.out_buffer_cv.notifyAll()

tests/integration_tests/modules/test_command_output.py: 127 warnings
  /home/holmanb/cloud-init-impish/.tox/integration-tests/lib/python3.10/site-packages/paramiko/buffered_pipe.py:104: DeprecationWarning: notifyAll() is deprecated, use notify_all() instead
    self._cv.notifyAll()

tests/integration_tests/modules/test_command_output.py: 104 warnings
  /home/holmanb/cloud-init-impish/.tox/integration-tests/lib/python3.10/site-packages/paramiko/buffered_pipe.py:206: DeprecationWarning: notifyAll() is deprecated, use notify_all() instead
    self._cv.notifyAll()

tests/integration_tests/modules/test_command_output.py: 26 warnings
  /home/holmanb/cloud-init-impish/.tox/integration-tests/lib/python3.10/site-packages/paramiko/channel.py:1233: DeprecationWarning: notifyAll() is deprecated, use notify_all() instead
    self.out_buffer_cv.notifyAll()

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
================= 1 passed, 298 warnings in 222.86s (0:03:42) ==================
___________________________________ summary ____________________________________
  integration-tests: commands succeeded
  congratulations :)
